name: weekly-publication-update
run-name: weekly member Google Scholar publication update

on:
  schedule:
    - cron: "0 12 * * 1"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-publications:
    uses: ./.github/workflows/update-citations.yaml
    secrets: inherit

  build-site:
    needs:
      - update-publications
    if: needs.update-publications.outputs.changed == 'true'
    uses: ./.github/workflows/build-site.yaml
